training.set=./datasets/mineral-Li/train.csv
test.set=./datasets/mineral-Li/test.csv
dev.set=./datasets/mineral-Li/dev.csv
model.name=MRLMRP
model.type=graph
item.ranking=-topN 10,20
embedding.size=64
num.max.epoch=300
batch_size=2048
learnRate=0.001
reg.lambda=0.0001
MRLMRP=-n_layer 3 -ssl_reg 1e-6 -proto_reg 1e-7 -tau 0.05 -hyper_layers 1 -alpha 1.5 -num_clusters 200
output.setup=-dir ./results/
seed=42
mineral_embedding_path=./pretrained_emb/mineral_embeddings_64.pt
mineral_dict_path=./datasets/mineral-Li/mineral_list.txt
